spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectws
    driverClassName: com.mysql.cj.jdbc.Driver
    username: wsuser
    password: WSuser2*25
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # Change to 'update' for production
    show-sql: false  # Set to false in production
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:f9217abb37b7fbde3ec155ed3b31ef76fcc46f3421f4c7229e0e5d2cf64171e9}
  expiration: 86400  # 24 hours

# Logging configuration
logging:
  level:
    com.feit.projectWS: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO

# Server configuration
server:
  port: 3306
  servlet:
    context-path: /

# CORS configuration
cors:
  allowed-origins: http://localhost:3000,http://localhost:8080
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# SOAP configuration
soap:
  wsdl-location: /ws
  service-name: EventsService