//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.01 at 09:28:36 PM CEST 
//


package com.feit.projectWS.events;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eventStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="eventStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FINISHED"/&gt;
 *     &lt;enumeration value="NOTFINISHED"/&gt;
 *     &lt;enumeration value="ACTIVE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "eventStatus")
@XmlEnum
public enum EventStatus {

    FINISHED,
    NOTFINISHED,
    ACTIVE;

    public String value() {
        return name();
    }

    public static EventStatus fromValue(String v) {
        return valueOf(v);
    }

}
