//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.31 at 01:11:29 PM CEST 
//


package com.feit.projectWS.events;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.feit.projectWS.events package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.feit.projectWS.events
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllEventsRequest }
     * 
     */
    public GetAllEventsRequest createGetAllEventsRequest() {
        return new GetAllEventsRequest();
    }

    /**
     * Create an instance of {@link GetAllEventsResponse }
     * 
     */
    public GetAllEventsResponse createGetAllEventsResponse() {
        return new GetAllEventsResponse();
    }

    /**
     * Create an instance of {@link EventList }
     * 
     */
    public EventList createEventList() {
        return new EventList();
    }

    /**
     * Create an instance of {@link GetEventByIdRequest }
     * 
     */
    public GetEventByIdRequest createGetEventByIdRequest() {
        return new GetEventByIdRequest();
    }

    /**
     * Create an instance of {@link GetEventByIdResponse }
     * 
     */
    public GetEventByIdResponse createGetEventByIdResponse() {
        return new GetEventByIdResponse();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link SearchEventsByNameRequest }
     * 
     */
    public SearchEventsByNameRequest createSearchEventsByNameRequest() {
        return new SearchEventsByNameRequest();
    }

    /**
     * Create an instance of {@link SearchEventsByNameResponse }
     * 
     */
    public SearchEventsByNameResponse createSearchEventsByNameResponse() {
        return new SearchEventsByNameResponse();
    }

    /**
     * Create an instance of {@link GetEventsByStatusRequest }
     * 
     */
    public GetEventsByStatusRequest createGetEventsByStatusRequest() {
        return new GetEventsByStatusRequest();
    }

    /**
     * Create an instance of {@link GetEventsByStatusResponse }
     * 
     */
    public GetEventsByStatusResponse createGetEventsByStatusResponse() {
        return new GetEventsByStatusResponse();
    }

    /**
     * Create an instance of {@link GetEventsByDateRequest }
     * 
     */
    public GetEventsByDateRequest createGetEventsByDateRequest() {
        return new GetEventsByDateRequest();
    }

    /**
     * Create an instance of {@link GetEventsByDateResponse }
     * 
     */
    public GetEventsByDateResponse createGetEventsByDateResponse() {
        return new GetEventsByDateResponse();
    }

    /**
     * Create an instance of {@link GetEventsByLengthRequest }
     * 
     */
    public GetEventsByLengthRequest createGetEventsByLengthRequest() {
        return new GetEventsByLengthRequest();
    }

    /**
     * Create an instance of {@link GetEventsByLengthResponse }
     * 
     */
    public GetEventsByLengthResponse createGetEventsByLengthResponse() {
        return new GetEventsByLengthResponse();
    }

    /**
     * Create an instance of {@link GetEventsByElevationGainRequest }
     * 
     */
    public GetEventsByElevationGainRequest createGetEventsByElevationGainRequest() {
        return new GetEventsByElevationGainRequest();
    }

    /**
     * Create an instance of {@link GetEventsByElevationGainResponse }
     * 
     */
    public GetEventsByElevationGainResponse createGetEventsByElevationGainResponse() {
        return new GetEventsByElevationGainResponse();
    }

    /**
     * Create an instance of {@link ServiceFault }
     * 
     */
    public ServiceFault createServiceFault() {
        return new ServiceFault();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link UserList }
     * 
     */
    public UserList createUserList() {
        return new UserList();
    }

}
