//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.02 at 12:24:29 AM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "localhost:8080/events", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.feit.projectWS.events;
