//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.31 at 01:11:29 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://projectWS.feit.com/events", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.feit.projectWS.events;
